/**
 * Accessible transient status messages for mod_videotrack players.
 *
 * The player core keeps a small facade for compatibility; this module owns the
 * DOM creation, ARIA attributes and auto-dismiss timer so YouTube, HTML5 and
 * Vimeo use the same feedback behaviour.
 *
 * @module mod_videotrack/core/status
 */
define([], function() {
    var states = new WeakMap();

    /**
     * Return timer state for a container without sharing timers across multiple
     * VideoTrack instances rendered on the same page.
     *
     * @param {HTMLElement} container Status container.
     * @returns {Object} Mutable timer state.
     */
    function getState(container) {
        if (!states.has(container)) {
            states.set(container, {timerId: null, announceTimerId: null});
        }
        return states.get(container);
    }
    var labels = {
        defaultMessage: 'Status update.',
        errorMessage: 'An error occurred. Please try again.',
        dismissMessage: 'Dismiss'
    };

    /**
     * Configure localised fallback labels used when callers provide empty text.
     *
     * @param {Object=} config Player configuration generated by PHP.
     */
    function configure(config) {
        config = config || {};
        labels.defaultMessage = (config.statusdefaultlabel || labels.defaultMessage).toString();
        labels.errorMessage = (config.statuserrorlabel || labels.errorMessage).toString();
        labels.dismissMessage = (config.dismisslabel || labels.dismissMessage).toString();
    }

    /**
     * Normalise user-visible message text and apply a localised fallback.
     *
     * @param {string} message Message supplied by caller.
     * @param {boolean} isError Whether the message is an error.
     * @returns {string} Safe non-empty status text.
     */
    function normaliseMessage(message, isError) {
        var text = (message || '').toString().trim();
        if (text) {
            return text;
        }
        return isError ? labels.errorMessage : labels.defaultMessage;
    }

    /**
     * Create or reuse a hidden live region for screen-reader announcements.
     *
     * @param {boolean} isError Whether assertive announcement is required.
     * @param {HTMLElement} container Preferred status container.
     * @returns {HTMLElement|null} Live region element.
     */
    function getLiveRegion(isError, container) {
        if (!container) {
            return null;
        }
        var selector = isError ? '.videotrack-status-live-assertive' : '.videotrack-status-live-polite';
        var region = container.querySelector(selector);
        if (region) {
            return region;
        }
        Array.prototype.forEach.call(container.querySelectorAll(
            isError ? '.videotrack-status-live-assertive' : '.videotrack-status-live-polite'
        ), function(existing) {
            existing.parentNode.removeChild(existing);
        });
        region = document.createElement('div');
        region.className = 'sr-only visually-hidden ' +
            (isError ? 'videotrack-status-live-assertive' : 'videotrack-status-live-polite');
        // The selected ARIA role already implies the expected politeness and atomicity.
        // Avoid duplicate aria-live/aria-atomic declarations, which can cause repeated
        // announcements in some screen reader/browser combinations.
        region.setAttribute('role', isError ? 'alert' : 'status');
        container.insertBefore(region, container.firstChild || null);
        return region;
    }

    /**
     * Remove a node if it is still attached to the document.
     *
     * @param {HTMLElement} node Status node.
     */
    function remove(node) {
        if (node && node.parentNode) {
            node.parentNode.removeChild(node);
        }
    }

    /**
     * Find the safest container for a status message.
     *
     * This fallback returns the first VideoTrack shell on the page. Callers that
     * need reliable targeting in multi-player pages must pass the container
     * explicitly to show(), announce() or clear().
     *
     * @returns {HTMLElement|null} Container element.
     */
    function getContainer() {
        return document.querySelector('.videotrack-player-shell') || document.body || null;
    }

    /**
     * Resolve the label used by the visible dismiss control.
     *
     * @param {string=} dismissLabel Caller-provided label.
     * @returns {string} Non-empty dismiss label.
     */
    function normaliseDismissLabel(dismissLabel) {
        var text = (dismissLabel || '').toString().trim();
        return text || labels.dismissMessage;
    }

    /**
     * Resolve the auto-dismiss timeout with conservative UX bounds.
     *
     * @param {boolean} isError Whether the notice is an error.
     * @param {number=} timeoutMs Requested timeout.
     * @returns {number} Timeout in milliseconds.
     */
    function normaliseTimeout(isError, timeoutMs) {
        var timeout = Number(timeoutMs);
        if (!Number.isFinite(timeout) || timeout <= 0) {
            return isError ? 12000 : 8000;
        }

        // Keep notices transient but readable; callers can still pass a longer
        // timeout for errors without leaving success messages around forever.
        var minimum = isError ? 6000 : 4000;
        var maximum = isError ? 30000 : 20000;
        return Math.min(Math.max(timeout, minimum), maximum);
    }

    /**
     * Announce a message through the shared live region without creating a visible notice.
     *
     * @param {string} message Message text.
     * @param {boolean=} isError Whether assertive announcement is required.
     * @param {HTMLElement=} container Preferred status container.
     */
    function announce(message, isError, container) {
        container = container || getContainer();
        if (!container) {
            return;
        }
        var text = normaliseMessage(message, !!isError);
        var state = getState(container);

        var region = getLiveRegion(!!isError, container);
        if (!region) {
            return;
        }

        if (state.announceTimerId) {
            window.clearTimeout(state.announceTimerId);
            state.announceTimerId = null;
        }

        // Clearing first makes repeated identical messages observable to assistive technology.
        region.textContent = '';
        state.announceTimerId = window.setTimeout(function() {
            region.textContent = text;
            state.announceTimerId = null;
        }, 30);
    }

    /**
     * Clear visible and hidden status messages.
     *
     * @param {HTMLElement=} container Preferred status container.
     */
    function clear(container) {
        var targets = container ? [container] : Array.prototype.slice.call(
            document.querySelectorAll('.videotrack-player-shell')
        );
        targets.forEach(function(target) {
            var state = getState(target);
            if (state.timerId) {
                window.clearTimeout(state.timerId);
                state.timerId = null;
            }
            if (state.announceTimerId) {
                window.clearTimeout(state.announceTimerId);
                state.announceTimerId = null;
            }
            remove(target.querySelector('.videotrack-status-message'));
            var polite = target.querySelector('.videotrack-status-live-polite');
            var assertive = target.querySelector('.videotrack-status-live-assertive');
            if (polite) {
                polite.textContent = '';
            }
            if (assertive) {
                assertive.textContent = '';
            }
        });
    }

    /**
     * Show a temporary accessible status message.
     *
     * @param {string} message Message text.
     * @param {boolean} isError Whether this is an error message.
     * @param {string=} dismissLabel Accessible label for dismiss button.
     * @param {number=} timeoutMs Auto-dismiss timeout in milliseconds.
     * @param {HTMLElement=} container Preferred status container. Required for
     * reliable targeting when more than one VideoTrack player is rendered.
     */
    function show(message, isError, dismissLabel, timeoutMs, container) {
        var text = normaliseMessage(message, !!isError);

        container = container || getContainer();
        if (!container) {
            return;
        }

        clear(container);

        var state = getState(container);
        announce(text, !!isError, container);

        var notice = document.createElement('div');
        notice.className = 'videotrack-status-message alert ' +
            (isError ? 'alert-danger' : 'alert-info') + ' alert-dismissible mt-2';
        notice.setAttribute('role', isError ? 'alert' : 'status');

        var span = document.createElement('span');
        span.textContent = text;
        notice.appendChild(span);

        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'close btn-close ms-2';
        button.setAttribute('aria-label', normaliseDismissLabel(dismissLabel));

        // Support both Moodle/Bootstrap 4 themes (`close`) and newer Bootstrap 5
        // themes (`btn-close`) while keeping an explicit text alternative.
        var closeIcon = document.createElement('span');
        closeIcon.setAttribute('aria-hidden', 'true');
        closeIcon.textContent = '\u00d7';
        button.appendChild(closeIcon);

        button.addEventListener('click', function() {
            if (state.timerId) {
                window.clearTimeout(state.timerId);
                state.timerId = null;
            }
            remove(notice);
        });
        notice.appendChild(button);

        container.insertBefore(notice, container.firstChild || null);

        var timeout = normaliseTimeout(!!isError, timeoutMs);
        state.timerId = window.setTimeout(function() {
            remove(notice);
            state.timerId = null;
        }, timeout);
    }

    return {
        configure: configure,
        announce: announce,
        clear: clear,
        show: show
    };
});
